// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdGp77MYPVXJuFxWBdBhG2VuA8hyUJrGs',
    appId: '1:768268579165:web:df7f997b1467ba786838b4',
    messagingSenderId: '768268579165',
    projectId: 'vegin-fd329',
    authDomain: 'vegin-fd329.firebaseapp.com',
    storageBucket: 'vegin-fd329.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3lw6Zse1K1YpR71Nwau6fgojTVklpgLM',
    appId: '1:768268579165:android:ece8442ee998e1a96838b4',
    messagingSenderId: '768268579165',
    projectId: 'vegin-fd329',
    storageBucket: 'vegin-fd329.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP84VlZefkw6vvjNlcLT9OCVYN1xD2wrM',
    appId: '1:768268579165:ios:9d9663924eac01ab6838b4',
    messagingSenderId: '768268579165',
    projectId: 'vegin-fd329',
    storageBucket: 'vegin-fd329.appspot.com',
    iosBundleId: 'com.example.vegin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP84VlZefkw6vvjNlcLT9OCVYN1xD2wrM',
    appId: '1:768268579165:ios:1f2480518a7dbb8d6838b4',
    messagingSenderId: '768268579165',
    projectId: 'vegin-fd329',
    storageBucket: 'vegin-fd329.appspot.com',
    iosBundleId: 'com.example.vegin.RunnerTests',
  );
}
